2024-08-25 01:38:58,716 - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Polina\PycharmProjects\Homework\Module12\tests_12_4.py", line 23, in test_run
    runner_1 = Runner(5, 7)
               ^^^^^^^^^^^^
  File "C:\Users\Polina\PycharmProjects\Homework\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-25 01:38:58,717 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Polina\PycharmProjects\Homework\Module12\tests_12_4.py", line 10, in test_walk
    runner_1 = Runner('Вося', -10)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Polina\PycharmProjects\Homework\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
